version: '3.6'

services:
  redis:
    build:
      context: ../build/redis
    volumes:
      - redis-socket:/run/redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'survey-manager'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'docker'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3333:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - survey-manager-db:/var/lib/mysql
      - ../init:/docker-entrypoint-initdb.d/:ro

  survey-manager-api:
    build:
      context: ../
    image: libellis/survey-manager-api:latest
    container_name: survey-manager
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      # For testing - update for prod
      - '8000:8000'
    expose:
      - '8000'
    environment:
      DATABASE_URL: "mysql://docker:password@mysql:3306/survey-manager" 
      CACHE_URL: "redis+unix:/run/redis/redis.sock"
    volumes:
      - redis-socket:/run/redis


# Names our volume
volumes:
  survey-manager-db:
  redis-socket:
